module.exports = {
  INIT_APP: 'INIT_APP',
  EXIT_APP: 'EXIT_APP',
  STATS_UPDATED: 'STATS_UPDATED',
  INTERVAL_CHANGED: 'INTERVAL_CHANGED',
  SETTINGS_CHANGED: 'SETTINGS_CHANGED',
  GET_SETTINGS: 'GET_SETTINGS',
}